### ISSUE TITLE
Support programmatic text in YAML metadata values

### ISSUE THREAD

**Issue by Witiko** [istqborg/istqb_product_base#46]
Our current approach in processing metadata always parses values in markdown text. Consider the following line of metadata:

``` yaml
logo: istqb_logo_ctfl
```

This line is currently parsed as istqb<em>logo</em>ctfl. This causes [difficult-to-debug errors][1] as discussed with @danopolan today.

### Tasks
- [x] During YAML validation in the CI, print a human-readable error when `logo` metadata values contain `_`.
- [x] Close https://github.com/Witiko/markdown/issues/440.
- [x] Use `jekyllDataProgrammaticString` renderers in the definition of the `istqb/common/metadata` setup snippet.
- [x] Update the Markdown package.
- [x] No longer check for the presence of `_` in `logo` metadata values during YAML validation in the CI.

 [1]: https://github.com/istqborg/istqb-ctfl/actions/runs/8922780004/job/24505748885
